### ISSUE TITLE
Docker for Windows service not starting: Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified

### ISSUE THREAD

**Issue by rupreetg** [Microsoft/DockerTools#126]
Docker on windows 10 not starting. Below is the error getting on 2 of my machines. 

Diagnostic ID:
A6ABB255-88C8-4BCF-ADA8-8CF60B615552/2018-06-27_12-01-29

Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified.

   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs:line 63
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 218
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 93
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 46
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 144

**Steps to reproduce:**
Install Docker for Windows
Change path as mentioned in [#1505](https://github.com/docker/for-win/issues/1505)
Restart machine
Start Dockers
It works for the first time but fails after that. 

**Not so effective workaround**
Reinstall docker after every docker build which seems to very unproductive.  
After first run, it'll again start failing and have to reinstall.

**Comment by rupreetg** [comment]
Simple docker info also not working. Only solution to this is reinstall. 

PS C:\WINDOWS\system32> docker info
docker : error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/info: open //./pipe/docker_engine: The system cannot find the 
file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also 
indicate that the docker daemon is not running.
At line:1 char:1
+ docker info
+ ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (error during co...is not running.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Tried restarted docker service, it starts and automatically stops. 

**Below is the error logged in eventviewer:**
_Error occurred when creating network could not find plugin internal in v1 plugin registry: plugin not found_

**Comment by geedsen** [comment]
Same here for me:

Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified.


   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs:line 63
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 46
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 144

In the log:
Failed to start COMProvider while calling CheckWorkstationCache.
[07:49:59.503][NamedPipeClient][Error  ] Unable to send Start: Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified.

**Comment by haniamr** [comment]
Closing the issue since that doesn't seem to be Visual Studio related, I'd start over here: https://github.com/docker/for-win/
