### ISSUE TITLE
Can't publish to custom repository that doesn't have https

### ISSUE THREAD

**Issue by Misiu** [microsoft/DockerTools#155]
I have a custom repository that I want to deploy my docker image to.
I've added my custom repository URL into Docker Settings:
![docker_insecure_repository](https://user-images.githubusercontent.com/1741838/47997596-aafeb600-e0fc-11e8-898e-a18a10398c4a.png)
I've created a simple ASP.NET Core 2.1 project in Visual Studio 15.8.9.

This is my Dockerfile:

```
FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ["DockerTestLinux/DockerTestLinux.csproj", "DockerTestLinux/"]
RUN dotnet restore "DockerTestLinux/DockerTestLinux.csproj"
COPY . .
WORKDIR "/src/DockerTestLinux"
RUN dotnet build "DockerTestLinux.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "DockerTestLinux.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "DockerTestLinux.dll"]
```

this is my pubxml file:

```
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <WebPublishMethod>Custom</WebPublishMethod>
    <DockerPublish>true</DockerPublish>
    <RegistryUrl>http://172.18.3.83:5000</RegistryUrl>
    <UserName />
    <PublishImageTag>latest</PublishImageTag>
    <PublishProvider>ContainerRegistry</PublishProvider>
    <LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>
    <LastUsedPlatform>Any CPU</LastUsedPlatform>
    <ProjectGuid>e345236e-5fa6-476d-9079-47711a444f5d</ProjectGuid>
  </PropertyGroup>
</Project>
```

When I click on Publish I get this error:
![docker_publish_error](https://user-images.githubusercontent.com/1741838/47997767-498b1700-e0fd-11e8-96d3-beceefc5278c.png)

and here are the details from diagnostic log file:

```
2018-11-05 13:10:16
Microsoft.VisualStudio.Web.Azure.Publish.Docker.DockerCommandException: Running the docker.exe login command failed.

WARNING! Using --password via the CLI is insecure. Use --password-stdin.Error response from daemon: Get https://172.18.3.83/v2/: dial tcp 172.18.3.83:443: connect: connection refused
   at Microsoft.VisualStudio.Web.Azure.Publish.ContainerRegistryProfileVisual.ThrowDockerCommandError(String dockerCommand)
   at Microsoft.VisualStudio.Web.Azure.Publish.ContainerRegistryProfileVisual.<DockerLoginAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.Web.Azure.Publish.ContainerRegistryProfileVisual.<PostPublishAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ApplicationCapabilities.Publish.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__127.MoveNext()
===================
```
As You can see during publish VS tries to access **https**://172.18.3.83:443, but I have insecure repository so it should use port 80 instead.

EDIT:
I've managed to push my image using CLI:
```
docker tag dockertestlinux 172.18.3.83:5000/dockertestlinux
docker push 172.18.3.83:5000/dockertestlinux
```

but ideally I would like to be able to do the same from Visual Studio.

**Comment by bwateratmsft** [comment]
Hey @Misiu , this is related to this [Developer Community issue](https://developercommunity.visualstudio.com/content/problem/361165/publishing-docker-image-to-custom-registry-fails.html), and should be fixed together with it.

**Comment by Misiu** [comment]
@bwateratmsft thank You for the link :)

**Comment by estiller** [comment]
Same here. Cannot push to private Azure Container Registry from Visual Studio. Using Visual Studio Enterprise 2019 (16.3.4).

11/10/2019 15:28:38
Microsoft.WebTools.Azure.Publish.Docker.DockerCommandException: Running the docker.exe login command failed.

WARNING! Using --password via the CLI is insecure. Use --password-stdin.Error response from daemon: Get https://XXX.azurecr.io:443/v2/: unauthorized: authentication required
   at Microsoft.WebTools.Azure.Publish.Docker.DockerOperations.ThrowDockerCommandError(String dockerCommand)
   at Microsoft.WebTools.Azure.Publish.Docker.DockerOperations.<DockerLoginAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WebTools.Azure.Publish.Docker.DockerPublish.<DockerPublishAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WebTools.Azure.Publish.ContainerRegistry.ManageContainerRegistry.<PushImageAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WebTools.Azure.Publish.PublishProviders.ContainerRegistryProfileVisual.<PostPublishAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__202.MoveNext()

**Comment by Levvy055** [comment]
Hitting the same wall. For custom container registry should be option to publish with already logged account.

**Comment by edobarnes** [comment]
Same error.

Microsoft Visual Studio Enterprise 2019 Version 16.5.4

We are trying to publish to a Docker instance on a network VM.

**Comment by KaFuzLuM** [comment]
Same error, Trying to publish container to Harbor instance. It keeps appending "/V2/" to the URL:
![image](https://user-images.githubusercontent.com/12032581/85926666-9bbc1580-b8a9-11ea-9cfe-8220a72db431.png)
VS 2019 16.4.3

**Comment by jvanlangen** [comment]
Any thoughts on this yet?

**Comment by godrejgpi** [comment]
Same issue with me. My **Docker Desktop is of version - 2.5.0.1 and VS version is - 16.7.6**

Getting below error:
`Publish has encountered an error.
Running the docker.exe login command failed.

WARNING! Using --password via the CLI is insecure. Use --password-stdin.

A diagnostic log has been written to the following location:
"C:\Users\Admin\AppData\Local\Temp\tmp2719.tmp"`

**Comment by jvanlangen** [comment]
I've managed it by adding the my custom repository by adding it to the Settings of your **local** docker engine. Create a section called insecure-registries.

This is an example of docker Settings => Docker Engine   (on windows)

```
{
  "registry-mirrors": [],
  "insecure-registries": [
    "MyRepo:5000"
  ],
  "debug": true,
  "experimental": false
}
```

**Comment by godrejgpi** [comment]
@jvanlangen  Thanks but I am actually trying to publish to Azure Container Registry (ACR) in the cloud and not local repository. I have created a new issue on this [link](https://github.com/MicrosoftDocs/visualstudio-docs/issues/6148).

I however tried your way and added "myrepo.azurecr.io" but it did not work. If you have any suggestions for me, kindly let me know. Thank you.

**Comment by swtrse** [comment]
> 
> 
> I've managed it by adding the my custom repository hostname/ip in the Settings of my **local** docker engine. Create a section called insecure-registries. Visual studio uses your local docker installation to publish an image to a remote repo. _(learned the hard way)_
> 
> This is an example of docker Settings => Docker Engine (on windows)
> 
> ```
> {
>   "registry-mirrors": [],
>   "insecure-registries": [
>     "MyRepo:5000"
>   ],
>   "debug": true,
>   "experimental": false
> }
> ```

This was exactly my problem. Thanks.

**Comment by LukasKubicek** [comment]
Same error 5 years later... Probably best not to count on Microsoft..

**Comment by dbreshears** [comment]
Closing stale issue.  This is an external issue which can be worked around with https://github.com/microsoft/DockerTools/issues/155#issuecomment-734338758
