### ISSUE TITLE
Could not install vsdbg to the remote runtime environment 'Docker dotnet/sdk'.

### ISSUE THREAD

**Issue by Varorbc** [microsoft/DockerTools#422]
```
Building Test Projects
========== Starting test run ==========
The remote debugger tools for .NET is required to debug tests. Attemtpting to auto install it at /usr/local/.vsdbg/
System.Exception: Could not install vsdbg to the remote runtime environment 'Docker dotnet/sdk'. This is required to debug tests.
Error: System.Collections.Generic.List`1[System.String]
   at Microsoft.VisualStudio.TestWindow.Host.TestPlatformProviders.BaseRemoteTestPlatformProvider.<PrepareForOperationAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.TestWindow.Host.TestPlatformProvider.<RunTestsAsync>d__30.MoveNext()
========== Test run aborted: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========
```

**Comment by dbreshears** [comment]
Hi @Varorbc.   The UnitTesting tools are maintained and supported by another team.   The best support for this option would be to create an issue on our Developer Community Channel -> https://developercommunity.visualstudio.com/VisualStudio/report
